### ISSUE TITLE
Mile CapCityTraveler Dialogue Freezes--Can't Exit

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#37]
1. Opened/logged in to game.
2. Travelled to Mile.
3. Opened interaction with "Traveler From the Capitol City," and first asked her about Mile.
4. Clicked on last remaining option, "Being Late," and the only thing that happens is the dev console reports, "KeyNotFoundException: The given key was not present in the dictionary." 
5. Without a way to continue the dialogue, the game is unplayable.

**Comment by jayvachon** [comment]
thanks matt - exceptions like these are almost always caused by typos in the yaml, so if you come across any more errors like this it would be best to double check the character's yaml file before submitting an issue. (in this case the "Being Late" key was not properly capitalized in capitol_city_traveler_malcom.yml)
