### ISSUE TITLE
Cannot confirm feedback scenario 1, year 1, poor management 1

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#403]
![screen shot 2015-10-01 at 12 51 23 pm](https://cloud.githubusercontent.com/assets/11821504/10227441/511d1510-683b-11e5-90f5-3b8cf1b24c7e.png)
effectively breaks the supervisor screen until the next year
causes text overlay on supervisor screen 

continues as a problem - not sure if this is because of the bug initially or if it has something to do with the individual scenario cards
![screen shot 2015-10-01 at 12 57 52 pm](https://cloud.githubusercontent.com/assets/11821504/10227577/27d4eb0a-683c-11e5-82b9-14a5e1a9ae8b.png)

**Comment by jpailthorpe** [comment]
I think this is because it is the last tactic card in them mix? at least thats how i reproduced this. There are no more tactics left in that year so I dont think the game knows what to do
![screen shot 2015-10-01 at 1 03 14 pm](https://cloud.githubusercontent.com/assets/10051544/10227694/d1e3de6c-683c-11e5-8e77-e3289f3d9876.png)

**Comment by jpailthorpe** [comment]
and thats why the overlay is happening 
![screen shot 2015-10-01 at 1 03 44 pm](https://cloud.githubusercontent.com/assets/10051544/10227704/e154add6-683c-11e5-851d-f203c6db7e33.png)

**Comment by jpailthorpe** [comment]
confirmed this is not a problem with yaml, but in it being the last tactic loaded for that year

**Comment by esalling23** [comment]
The overlay happens when waiting for feedback, investigating, or on the confirm feedback screen when the year ends.
