### ISSUE TITLE
phase 1: tutorial breaks game 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#428]
1. started with tutorial 
2. finished tutorial, except when in plan screen, did not drag a tactic into the slot. Instead, just closed the notebook.
3. was out on the map ready to go to a new city. 
4. opened notebook. 
5. when i dragged a tactic in, the notebook button was still greyed out, unclickable. Game is broken. 

![screen shot 2015-10-15 at 5 28 56 pm](https://cloud.githubusercontent.com/assets/10051544/10528131/55c7865e-7362-11e5-9428-ad4bda92c5da.png)

**Comment by esalling23** [comment]
The bug will also occur following these steps : 
- start tutorial
- move through the capital city, until out of conversation points
- sent to map, but instead of clicking a city, goes to tactic screen
- from here, the buttons to return to the map are disabled, causing the player to be stuck in the tactic plan screen 

on Windows and Mac

**Comment by esalling23** [comment]
1. skip tutorial
2. get sent to map
3. go to tactic screen
4. both buttons are disabled- cannot return to map

**Comment by johnnycrich** [comment]
Will be fixed in next build.
